### PR TITLE
Add new landing page

### PR DESCRIPTION
**Pull request by laurentmih**
The purpose of this MR is to add a new landing page that provides a bit more orientation, especially to first-time users. Some open questions I have:  
* What else should the initial page include?
* How are normal images/screenshots handled? Tried doing it with LFS GitHub complained
* should I add a link to the Matrix chat for people looking for support?

Happy to get feedback. Once this is done, my idea would be to create some kind of "guided exploration" subtree in which various workflow screenshots are looked at etc, and dissecting that a bit.

### CODE REVIEW

**Comment by BlenderNeko** [comment]
Couple of things about the PR:

* I don't think it is wise to link to PRs in the docs, especially not on the landing page. If we absolutely must it should have sufficient amount of warning signs in front of it.
* I don't think we should refer to the output as "gens", there is no good reason to shorten these kinds of things, just use e.g. generated output/images etc.
* The docs are build with the [Keys](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#keys) extension enabled so we have fancy ways of displaying keybinds
* Users can also load workflows via drag and drop.
* I don't really want to endorse specific image/file hosting websites, we can leave that choice to the user.

About your questions:
* My initial vision for the landing page would be to help the user set up ComfyUI, guide them through a simple task inside ComfyUI, and finally help them navigate the rest of the docs by explaining what is in them and point them towards other sections that might be of their interest. This last bit is a bit though right now though, as the docs are still quite incomplete.
* I set this up without much knowledge of github-pages, so any suggestions would be welcome. Currently the images are just uploaded to the repo.
* It would probably be a good idea to have a section dedicated to additional resources, it could go there. Though perhaps the Matrix channel is important enough to go into the landing page or perhaphs even the footer.

I have plans to associate every node in the doc with an example workflow, though taking a user by the hand and guiding them through one or two of them from start to finish might not be a bad idea. I don't really want to make this a gallery of workflows though, there are other places where they could get that experience and we can link to those places in the additional resources section.

**Comment by laurentmih** [comment]
Alright, so:

- [x] Removed the mention of a PR and Docker, I'm guessing it's too vague at the moment to be of use anyways
- [x] removed the "gen" language
- [x] made stuff fancy with keys
- [x] mentioned drag and drop
- [x] removed specific image website mention
- [x] Added the matrix link to the top of the page

For the rest:  
* For your vision, I feel like we're there as a first version, though obviously missing the "explore further" part - hopefully that comes as we flesh it out a bit. do you feel anything is still missing otherwise from the landing page?
* images, honestly, i'm not sure what to tell you. The imo correct way would be to do it via LFS, that's what it was designed for. Unfortunately, you can't use LFS if you're working through a forked repo (??? thanks GH). Uploading images directly to the repo is viable short-term, but given they're binary, `git` won't be able to diff them, leading to an exploding repo size. there's hacks from what i could tell online, but they look, well, like hacks. not sure how to solve this longer term. I'd still be down for LFS, but aside from the workflow limitations, there's only 1GB of storage allowed, after that it's $60 for 60GB per year...

**Comment by laurentmih** [comment]
It turns out that you can just export all workflows into SVG (as I think is stated in the docs), so I'll just add an SVG of the workflow. That doesn't really answer the part about showing PNGs, but it does solve the matter at least partially

**Comment by BlenderNeko** [comment]
made a couple of small changes to the page

**Pull request merged**
